export const FETCH_ELEMENTS_START = "FETCH_ELEMENTS_START";
export const FETCH_ELEMENTS_SUCCESS = "FETCH_ELEMENTS_SUCCESS";
export const FETCH_ELEMENTS_FAILURE = "FETCH_ELEMENTS_FAILURE";

export const FETCH_SINGLE_ELEMENTS_LINK_START =
  "FETCH_SINGLE_ELEMENTS_LINK_START";
export const FETCH_SINGLE_ELEMENTS_LINK_SUCCESS =
  "FETCH_SINGLE_ELEMENTS_LINK_SUCCESS";
export const FETCH_SINGLE_ELEMENTS_LINK_FAILURE =
  "FETCH_SINGLE_ELEMENTS_LINK_FAILURE";

export const CREATE_ELEMENTS = "CREATE_ELEMENTS";
export const UPDATE_ELEMENTS = "UPDATE_ELEMENTS";
export const DELETE_ELEMENTS = "DELETE_ELEMENTS";

export const FETCH_LOOK_UPS_START = "FETCH_LOOK_UPS_START";
export const FETCH_LOOK_UPS_SUCCESS = "FETCH_LOOK_UPS_SUCCESS";
export const FETCH_LOOK_UPS_FAILURE = "FETCH_LOOK_UPS_FAILURE";

export const FETCH_LOOK_UPS_VALUES_START = "FETCH_LOOK_UPS_VALUES_START";
export const FETCH_LOOK_UPS_VALUES_SUCCESS = "FETCH_LOOK_UPS_VALUES_SUCCESS";
export const FETCH_LOOK_UPS_VALUES_FAILURE = "FETCH_LOOK_UPS_VALUES_FAILURE";
