export const FETCH_ELEMENTS_START = "FETCH_ELEMENTS_START";
export const FETCH_ELEMENTS_SUCCESS = "FETCH_ELEMENTS_SUCCESS";
export const FETCH_ELEMENTS_FAILURE = "FETCH_ELEMENTS_FAILURE";

export const FETCH_SINGLE_ELEMENTS_LINK_START =
  "FETCH_SINGLE_ELEMENTS_LINK_START";
export const FETCH_SINGLE_ELEMENTS_LINK_SUCCESS =
  "FETCH_SINGLE_ELEMENTS_LINK_SUCCESS";
export const FETCH_SINGLE_ELEMENTS_LINK_FAILURE =
  "FETCH_SINGLE_ELEMENTS_LINK_FAILURE";

const CREATE_ELEMENTS = "CREATE_ELEMENTS";
const UPDATE_ELEMENTS = "UPDATE_ELEMENTS";
const DELETE_ELEMENTS = "DELETE_ELEMENTS";
